#  CalibratedSimulationFunctions 

### calibratedSimulationFunctions.R 
DesignTable : function (DataList, methods, MC_replicates = 100, columnames = NULL, filename = NULL, DoHistograms = F)  
ExpectedRegret : function (wavesizes, C, theta, methods, R)  
PrintRegretHistogram : function (shareTreatmentsList, filename, dataname, MC_replicates, waves)  
PrintRegretTable : function (RegretTable, filename, caption, MC_replicates, nmethods)  
SimulateTWaveDesign : function (wavesizes, C, theta, method = "modifiedthompson")  



### ReadData.R 
DataToTheta : function (filename, dataname, k, strataVars, outcomename, treatmentname, covariatesnames, printFigures = FALSE)  
print_one_datafigure : function (DataList)  
PrintDataFigures : function (stratasizes, sumstats, theta, filename, dataname, outcomename, treatmentname, k)  
ReadAllData : function (printFigures = F)  



#  IllustrationFunctions 

### Illustration_NonConvexity_Functions.R 
MSEcalc : function (theta, N)  
powerCalc : function (theta, N)  
stylizedDesign : function (A, B, C, N)  



#  OptimalAssignmentFunctions 

### SimulatedWelfareFunctions.R 
Seed : function (A, B, Nmax)  
simplex : function (N, k, coverage = "full", RR = 500, thetahat = NULL)  
simulatedSample : function (D, theta)  
Uhat : function (A, B, C, n, Vfunction = SWF)  



### TreatmentAssignmentFunctions.R 
Dtchoice : function (A, B, C, Nt, method = "optimal")  
EqualAssignment : function (N, k)  
GivenAssignment : function (n, k)  
ProportionalAssignment : function (Shares, Nt)  
Thompson : function (A, B, Nt)  
ThompsonProbabilities : function (A, B, RR = 1000)  



### WelfareFunctions.R 
betabinomial : function (n, s, a, b)  
betaposterior : function (D, Y)  
PolicyChoice : function (A, B, C)  
Regret : function (D, Y, C, theta)  
SWF : function (A, B, C)  
U : function (A, B, C, n, Vfunction = SWF)  
UoverSimplex : function (A, B, C, N, Ufunction = U, coverage = "full")  
V : function (A, B, C, NN)  



### welfareplotsGraphics.R 
OptimalPilot : function (A, B, C, M, parallel = TRUE)  
PlotOptimalAssignment : function (n1, N2, k = 3)  
PlotSimplex : function (A, B, C, N)  
PlotSimplexAlternative : function (A, B, C, N)  
SimplexPanel : function (N, alternativeplot = FALSE)  
ThompsonMappingPlots : function (p_list)  



#  ThompsonHierarchicalFunctions 

### calibratedSimulationFunctionsCovariates.R 
DesignTableCovariates : function (DataList, methods, MC_replicates = 100, columnames = NULL, filename = NULL)  
ExpectedRegretCovariates : function (wavesizes, C, theta, PX, methods, R)  
SimulateTWaveDesignCovariates : function (wavesizes, C, theta, PX, method = "stratified")  
SimulateX : function (PX, N)  
SimulateY : function (theta, D, X)  



### functionlist.Rmd 



### MCMC_HierarchicalThompson.R 
draw.alpha : function (alpha, beta, theta, prop.sd, nx)  
draw.beta : function (alpha, beta, theta, prop.sd, nx)  
draw.thetas : function (alpha, beta, NNd, SSd, nx)  
DtchoiceCovariates : function (Y, D, X, k, nx, Xt, method = "stratified")  
DtchoiceMCMCProbabilities : function (Y, D, X, k, nx, C = rep(0, k), RR = 2000)  
DtchoiceThompsonHierarchical : function (Y, D, X, k, nx, Xt)  
DtchoiceThompsonHierarchicalExpected : function (Y, D, X, k, nx, Xt)  
DtchoiceThompsonHierarchicalModified : function (Y, D, X, k, nx, Xt)  
hierarchicalPosteriorMean : function (Y, D, X, k, nx)  
log.prior : function (alpha, beta)  
ProportionalAssignment : function (Shares, nt)  
sample.theta.d : function (NNd, SSd, nx, RR = 2000)  
StratifiedAssignment : function (X, k, nx)  



### ThompsonHierarchical_old.R 
betabinomialMLE : function (NN, SS)  
DtchoiceCovariates : function (Y, D, X, k, nx, Xt, method = "stratified")  
DtchoiceThompson : function (Y, D, k, Nt)  
DtchoiceThompsonHierarchical : function (Y, D, X, k, nx, Xt)  
DtchoiceThompsonHierarchicalAlternating : function (Y, D, X, k, nx, Xt)  
DtchoiceThompsonHierarchicalModified : function (Y, D, X, k, nx, Xt, RR)  
DtchoiceThompsonModified : function (Y, D, k, Nt, RR)  
hierarchicalPosteriorDraw : function (NN, SS, LLH, AB = NULL)  
hierarchicalPosteriorMean : function (Y, D, X, empiricalBayes = T, draws = 1000)  
SimulateX : function (PX, N)  
SimulateY : function (theta, D, X)  
StratifiedAssignment : function (X, k, nx)  



